# Task 1

# 1. 
Write a function to compute 5/0 and use try/except to catch the exceptions.

In [6]:
def get_div():
    num=int(input('Enter the Numerator: '))
    den=int(input('Enter the Denominator: '))
    try:
        return num/den
    except (ZeroDivisionError, Exception ) as y :
        print("Error Type: {}. Division by zero is not allowed.Try other value for denominator.".format(y))
        
get_div()

Enter the Numerator: 5
Enter the Denominator: 0
Error Type: division by zero. Division by zero is not allowed.Try other value for denominator.


# 2. 
Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]

In [14]:
def sentence(subjects,verbs,objs):
    for sent in [f'{subj} {verb} {obj}' for subj in subjects for verb in verbs for obj in objs]:
        print(sent)
    

sub=["Americans","Indians"] 
verb=["play","watch"] 
obj=["Baseball","Cricket"]

w=sentence(sub,verb,obj)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2

1. Write a function so that the columns of the output matrix are powers of the input vector
The order of the powers is determined by the increasing boolean argument.Specifically,when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

    HINT:Such amatrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [16]:
import numpy as np
def gen_vander_matrix(inp_vec, N=None, increasing = False):
    
    if N == None : N = len(inp_vec)
    if increasing:
        op_matrix = [[element**power for power in range(0, N)] for element in inp_vec]
        print(np.row_stack(op_matrix))
    else:
        op_matrix = [[element**power for power in range(N-1, -1, -1)] for element in inp_vec]
        print(np.row_stack(op_matrix))

gen_vander_matrix([1, 2, 3, 5])

gen_vander_matrix([1, 2, 3, 5],N=5)

gen_vander_matrix([1, 2, 3, 5],N=5,increasing = True)

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   5  25 125 625]]
